### ISSUE TITLE
Define Dev Instructions in Readme 

### ISSUE THREAD

**Issue by UraniumDonut** [Ballmaid/UnderwaterRestaurantGame#1]
Readme.md should have instructions on how to open the Project including information like Unity Version etc.

**Comment by Ballmaid** [comment]
Good idea, I will try to specify all requirements

**Comment by UraniumDonut** [comment]
Fixed in https://github.com/Ballmaid/UnderwaterRestaurantGame/commit/59074639a0669df1865b4bfdf00d5f7327d9e958
